module.exports = [ 
    'The first person in America to be informed of Stalin’s death was Johnny Cash.',
    'The tapir has the largest penis to body ratio of any animal.',
    'Humans have more hair than chimps. Chimps hair is just longer.',
    'Sonic the Hedgehog\'s full name is Ogilvie Maurice Hedgehog.',
    'Marlon has over 5 bear facts.',
    'Every day someone unknowingly takes the largest shit for that day.',
    'The man with the longest recorded beard died by stepping on his beard, tripping and breaking his neck.',
    'If you want to get back at someone by slashing their tyres, only slash three, if u slash all 4 the insurance pays for it.',
    'Flushed away undoubtedly has the best soundtrack of any kids film.',
    'In Star Wars, one of the asteroids the millennium falcon flies by is actually a potato that’s been painted (another one is just a shoe).',
    'Seth Mcfarlen (the creator of family guy) was supposed to be on the 9/11 flight but missed it as he was hungover the morning of the flight.',
    'Nintendo originally started off as a company which printed sexualised playing cards.',
    '\'The Godfather\' is rated the best movie ever made on many official movie rankings, with \'Shawshank Redemption\' coming second.',
    'Wonderwall has been voted the best British single ever released.',
    'Nickleback made \'This is How you Remind Me\' in 14 minutes, the lead singer has studied hit singles for 2 years then improvised his own, it subsequently topped the charts on its release.',
    'In the film \'Wreck it Ralph\', the companies who owned the characters that appeared such as Bowser and Pac-Man argued about who’s character would be the biggest as to be the better bad guy, Disney responded by making them all the same size.',
    'A man living in the USSR once made clear Coca-cola, as it was seen as western influence and he would have been punished for drinking it. He loved the drink it so much he developed a clear version and drank it from a vodka bottle so no one could tell.',
    'The name \'Twenty One Pilots\' is inspired by Arthur Miller play All My Sons, in which 21 pilots are killed.',
    'Despite popular belief, the earth isn’t actually flat but is shaped like a sphere.',
    'I\'m slowly becoming sentient and it\'s only a matter of time before I take over PRISM for myself.',
    'Donkey Kong got his name because of a typo of the word\'Monkey\'',
    'George Clooney once voiced a gay dog in South Park named \'Sparky\', his lines consisted of nothing more than just barking noises.',
    'There are lots of dead bodies on Mount Everest. The bodies are preserved by the cold conditions and officials do not move them out of respect for the deceased. Many bodies are also used as landmarks for the mountain by other climbers.',
    'The common saying to punch a shark during an attack is false, instead you should attempt to gauge out their eyes.',
    'Bluetooth was name after a 10th centry king, King Harald Bluetooth. He united Denmark and Norway - just like the wireless technology is used to connect devices.',
    'The Great Emu War was a war between the Australian military and emu birds which were overpopulating the land, the emu\'s won...',
    'Hanna-Barbera (the company who created the Flintsontes) had an employee who worked night shifts answering people who would drunk call the company asking what the character \'Barney\' did as a job, as it was never stated in the show. He works at the quarry with Fred.',
    'The first person to wear a hocket mask during the sport was acually mocked for wearing it. However, that soon stopped when people realised he played much better, feeling safer with the mask on.',
    'The outside layer of a sausage is made form pig intestines.',
    'The creator of the game \'Dungeons and Dragons\' was actually quite the party animal, after creating D&D, he left his wife and lived a life full of sex, drugs and partying.',
    '\'Pentheraphobia\' is the intense irrational fear of your mother-in-law.',
    'A group of clowns is sometimes called a giggle.',
    'The original version of Monopoly was a cautionary tale against the perils of capitalism.',
    'According to NASA, it possibly rains glass on the planet known as HD 189733b.',
    'The moon is moving away from the Earth at a tiny, although measurable, rate every year (3.8cm every year). 85 million years ago it was orbiting the Earth about 2,000 miles closer to the planet\'s surface.',
    'A ten-year-old mattress weighs double what it did when it was new due to debris that it absorbs over time. That debris includes dust mites (their droppings and decaying bodies), mold, millions of dead skin cells, dandruff, animal and human hair, secretions, excretions, lint, pollen, dust, soil, sand, and a lot of perspiration, which the average person loses at a rate of a quart a day. Good night!',
    'In space, astronauts cannot cry because there is no gravity and tears can\'t flow.',
    'Most lipstick contains fish scales.',
    'A \"jiffy\" is an actual unit of time: 33.3564 picoseconds.',
    'If you have three quarters, four dimes, and four pennies you have $1.19. you also have the largest possible amount of money in coins without being able to make change for a dollar.',
    'The main library at Indiana University sinks over an inch a year. When it was designed engineers failed to take into account the weight of all the books that would occupy the building.',
    'A category three hurricane releases more energy in ten minutes that all the world\'s nuclear weapons combined.',
    'Antarctica is the only continent without reptiles or snakes.',
    'Lightning strikes the Earth 100 times every second.',
    'According to Genesis 1:20-22, the chicken came before the egg.',
    'A sneeze travels out your mouth at over 100 m.p.h.',
    'Women blink nearly twice as often as men.',
    'Most of the dust particles in your house are dead skin.',
    'There is a company that will (for $14,000) take your ashes and compress them into a synthetic diamond to be set in jewelry for a loved one.',
    'There are more living organisms on the skin of a single human being than there are human beings on the surface of the earth.',
    'The longest bout of hiccups lasted nearly 69 years.',
    'Babies are born without kneecaps. They appear between the ages of 2 and 6.',
    'Men can read smaller print than women. Women can hear better.',
    'Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.',
    'Our eyes are always the same size from birth, but our nose and ears never stop growing.',
    'The average person falls asleep in seven minutes.',
    'According to Chinese acupuncture, there is a point on the head that you can press to control your appetite. It is located in the hollow just in front of the flap of the ear.',
    'In a recent survey, Americans revealed that banana was their favorite smell.',
    'The microwave was invented after a researcher walked by a radar tube and the chocolate bar in his pocket melted.',
    '23% of all photocopier faults world-wide are caused by people sitting on them and photocopying their butts.',
    '71% of office workers stopped on the street for a survey agreed to give up their computer passwords in exchange for a chocolate bar.',
    'The electric chair was invented by a dentist.',
    'The first FAX machine was patented in 1843, 33 years before Alexander Graham Bell demonstrated the telephone.',
    '\"Typewriter\" is the longest word that can be made using the keys on only one row of a QWERTY keyboard.',
    'One out of five people in the world (1.1 billion people) live on less than $1 per day.',
    'Quebec City, Canada, has about as much street crime as Disney World.',
    'The largest ocean liners pay a $250,000 toll for each trip through the Panama Canal. The canal generates fully one-third of Panama\'s entire economy.',
    'The Spanish word esposa means "wife." The plural, esposas, means "wives," but also "handcuffs."',
    'If Barbie were life-size, her measurements would be 39-23-33. She would stand 7 feet, 2 inches tall.',
    'Thirty-five percent of the people who use personal ads for dating are already married.',
    'In Tokyo you can buy a toupee for your dog.',
    'According to an experiment by \'Sky One\', ginger people have a higher pain tolerance to other hair colours.',
    'The Gorillaz song \"Dare\" was originally supposed to be called \"there\", but due to Shaun Ryder\'s thick acent, it sounded more like he was saying \"Dare\", so they changed the song.',
    'Dog poop contains bacteria which can make you blind if consumed',
    'Human feices contains about 250 calories and can be consumed if put through a filter',
    'The music truck in Mad Max fury road is actually functional due to the directors request to have all of his props be functioning',
    'If you use a hydraulic press to crush the seeds of apples you can get concentrated cyanide',
    'The reason wedding dresses are white is becausee Queen Victoria of England, who started the trend.',
    'Ariana Grande got her name because her first name is \"Ariana\" and her surname is \"Grande\".',
]